apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: jpetstore-cb-workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout
        with:
          provider: github
          repository: jpetstore-6
      - uses: docker://maven:3-eclipse-temurin-17
        name: Maven build
        shell: sh
        run: |
          mvn clean verify -Dtest="*,!MySql*,!Postgres*"
  SonarQube:
    steps:
      - uses: cloudbees-io/sonarqube-sast-scan-code@v1
        name: Run SonarQube scan
        kind: scan
        with:
          server-url: https://sonar.cloudbees.guru:9000
          username: admin
          password: ${{ secrets.sonarqube_cloudbees_guru }}
    needs:
      - build
