apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: jpetstore-cb-workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout
        with:
          provider: github
          repository: manav20052022/jpetstore-6
      - uses: docker://maven:3-eclipse-temurin-17
        name: Maven build
        shell: sh
        run: |
          mvn package 
